//
// Generated file, do not edit! Created by nedtool 5.6 from ARP.msg.
//

#ifndef __ARP_M_H
#define __ARP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ARP.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ARP
 * {
 *     short oper;
 *     char smac[17];//
 *     char spa[7];
 *     char dmac[17];
 *     char tpa[7];
 * }
 * </pre>
 */
class ARP : public ::omnetpp::cPacket
{
  protected:
    short oper;
    char smac[17];
    char spa[7];
    char dmac[17];
    char tpa[7];

  private:
    void copy(const ARP& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ARP&);

  public:
    ARP(const char *name=nullptr, short kind=0);
    ARP(const ARP& other);
    virtual ~ARP();
    ARP& operator=(const ARP& other);
    virtual ARP *dup() const override {return new ARP(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual short getOper() const;
    virtual void setOper(short oper);
    virtual unsigned int getSmacArraySize() const;
    virtual char getSmac(unsigned int k) const;
    virtual void setSmac(unsigned int k, char smac);
    virtual unsigned int getSpaArraySize() const;
    virtual char getSpa(unsigned int k) const;
    virtual void setSpa(unsigned int k, char spa);
    virtual unsigned int getDmacArraySize() const;
    virtual char getDmac(unsigned int k) const;
    virtual void setDmac(unsigned int k, char dmac);
    virtual unsigned int getTpaArraySize() const;
    virtual char getTpa(unsigned int k) const;
    virtual void setTpa(unsigned int k, char tpa);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ARP& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ARP& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ARP_M_H

