//
// Generated file, do not edit! Created by nedtool 5.6 from Eth_pck.msg.
//

#ifndef __ETH_PCK_M_H
#define __ETH_PCK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Eth_pck.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Eth_pck
 * {
 *     int64_t preamble = 0xAAAAAAAAAAAAAAAB;
 *     char sMAC[6];
 *     char dMAC[6];
 *     short Length;
 *     int crc;
 * }
 * </pre>
 */
class Eth_pck : public ::omnetpp::cPacket
{
  protected:
    int64_t preamble;
    char sMAC[6];
    char dMAC[6];
    short Length;
    int crc;

  private:
    void copy(const Eth_pck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Eth_pck&);

  public:
    Eth_pck(const char *name=nullptr, short kind=0);
    Eth_pck(const Eth_pck& other);
    virtual ~Eth_pck();
    Eth_pck& operator=(const Eth_pck& other);
    virtual Eth_pck *dup() const override {return new Eth_pck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int64_t getPreamble() const;
    virtual void setPreamble(int64_t preamble);
    virtual unsigned int getSMACArraySize() const;
    virtual char getSMAC(unsigned int k) const;
    virtual void setSMAC(unsigned int k, char sMAC);
    virtual unsigned int getDMACArraySize() const;
    virtual char getDMAC(unsigned int k) const;
    virtual void setDMAC(unsigned int k, char dMAC);
    virtual short getLength() const;
    virtual void setLength(short Length);
    virtual int getCrc() const;
    virtual void setCrc(int crc);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Eth_pck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Eth_pck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ETH_PCK_M_H

